name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - master

stages:
- stage: BuildAndRunUnitTests
  displayName: Build and run unit tests
  pool:
    vmImage: 'ubuntu-18.04'
  jobs:
  - job: BuildAndRunUnitTests

    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'clean build'

- stage: PublishSnapshot
  displayName: Publish SNAPSHOT
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'Manual')))
  pool:
    vmImage: 'ubuntu-18.04'
  jobs:
  - job: PublishSnapshot

    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download gradle.properties'
      name: gradle_properties
      inputs:
        secureFile: 'gradle.properties'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Moving gradle.property file.'
          mkdir ~/.gradle
          mv -f $(gradle_properties.secureFilePath) ~/.gradle/
        failOnStderr: true

    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'artifactoryPublish'